apiVersion: source.toolkit.fluxcd.io/v1beta1
kind: GitRepository
metadata:
  name: alpine
  namespace: default
spec:
  interval: 30s
  ref:
    branch: master
  url: https://github.com/developer-guy/pwned-desired-state-repository
